/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/': RouteRecordInfo<'/admin/', '/admin', Record<never, never>, Record<never, never>>,
    '/dashboard/': RouteRecordInfo<'/dashboard/', '/dashboard', Record<never, never>, Record<never, never>>,
    '/dashboard/raksti/[id]/rediget': RouteRecordInfo<'/dashboard/raksti/[id]/rediget', '/dashboard/raksti/:id/rediget', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/dashboard/raksti/izveidot': RouteRecordInfo<'/dashboard/raksti/izveidot', '/dashboard/raksti/izveidot', Record<never, never>, Record<never, never>>,
    '/kategorijas': RouteRecordInfo<'/kategorijas', '/kategorijas', Record<never, never>, Record<never, never>>,
    '/login': RouteRecordInfo<'/login', '/login', Record<never, never>, Record<never, never>>,
    '/raksti/': RouteRecordInfo<'/raksti/', '/raksti', Record<never, never>, Record<never, never>>,
    '/raksti/[slug]': RouteRecordInfo<'/raksti/[slug]', '/raksti/:slug', { slug: ParamValue<true> }, { slug: ParamValue<false> }>,
    '/register': RouteRecordInfo<'/register', '/register', Record<never, never>, Record<never, never>>,
    '/statistika': RouteRecordInfo<'/statistika', '/statistika', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin/index.vue': {
      routes: '/admin/'
      views: never
    }
    'src/pages/dashboard/index.vue': {
      routes: '/dashboard/'
      views: never
    }
    'src/pages/dashboard/raksti/[id]/rediget.vue': {
      routes: '/dashboard/raksti/[id]/rediget'
      views: never
    }
    'src/pages/dashboard/raksti/izveidot.vue': {
      routes: '/dashboard/raksti/izveidot'
      views: never
    }
    'src/pages/kategorijas.vue': {
      routes: '/kategorijas'
      views: never
    }
    'src/pages/login.vue': {
      routes: '/login'
      views: never
    }
    'src/pages/raksti/index.vue': {
      routes: '/raksti/'
      views: never
    }
    'src/pages/raksti/[slug].vue': {
      routes: '/raksti/[slug]'
      views: never
    }
    'src/pages/register.vue': {
      routes: '/register'
      views: never
    }
    'src/pages/statistika.vue': {
      routes: '/statistika'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
